services:
  maindatabase:
    image: postgres:18
    container_name: maindatabase
    ports:
      - "35432:5432"
    environment:
      POSTGRES_DB: jbof
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - "./docker/postgres:/var/lib/postgresql"
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ AMQP
      - "15672:15672" # RabbitMQ Web UI # TODO: delete for prod
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9002:9002" # MinIO S3 API
      - "9003:9003" # MinIO Console UI TODO: DELETE FOR PROD
    volumes:
      - ./docker/minio:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    restart: unless-stopped
