spring.config.import=optional:file:.env[.properties]

server.port=${SERVER_PORT}
spring.application.name=${SPRING_APPLICATION_NAME}

# multipart limits
spring.servlet.multipart.max-file-size=${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE}
spring.servlet.multipart.max-request-size=${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE}
server.tomcat.max-http-form-post-size=${SERVER_TOMCAT_MAX_HTTP_FORM_POST_SIZE}
server.tomcat.max-swallow-size=${SERVER_TOMCAT_MAX_SWALLOW_SIZE}

# postgres
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# jpa / hibernate
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.open-in-view=${SPRING_JPA_OPEN_IN_VIEW}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}
spring.jpa.properties.hibernate.jdbc.time_zone=${SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_TIME_ZONE}

# optional, usually Hibernate can detect it anyway
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}

# migrations
spring.flyway.enabled=${SPRING_FLYWAY_ENABLED}
spring.flyway.locations=${SPRING_FLYWAY_LOCATIONS}

# MinIO / S3
storage.s3.endpoint=${STORAGE_S3_ENDPOINT}
storage.s3.access-key=${STORAGE_S3_ACCESS_KEY}
storage.s3.secret-key=${STORAGE_S3_SECRET_KEY}
storage.s3.region=${STORAGE_S3_REGION}
storage.s3.path-style=${STORAGE_S3_PATH_STYLE}

# Multipart
multipart.max-file-size=${MULTIPART_MAX_FILE_SIZE}
multipart.max-request-size=${MULTIPART_MAX_REQUEST_SIZE}

# QUEUE
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD}
spring.rabbitmq.virtual-host=${SPRING_RABBITMQ_VIRTUAL_HOST}
spring.rabbitmq.listener.simple.default-requeue-rejected=${SPRING_RABBITMQ_LISTENER_SIMPLE_DEFAULT_REQUEUE_REJECTED}
spring.rabbitmq.template.mandatory=${SPRING_RABBITMQ_TEMPLATE_MANDATORY}

pagination.max-page-size=${PAGINATION_MAX_PAGE_SIZE}
pagination.default-page-size=${PAGINATION_DEFAULT_SIZE}

app.rabbitmq.default-exchange=${APP_RABBITMQ_DEFAULT_EXCHANGE}
app.rabbitmq.default-routing-key=${APP_RABBITMQ_DEFAULT_ROUTING_KEY}
app.rabbitmq.receive-timeout=${APP_RABBITMQ_RECEIVE_TIMEOUT}
app.rabbitmq.media-processing-queue=${APP_RABBITMQ_MEDIA_PROCESSING_QUEUE}

cors.frontend-url=${CORS_FRONTEND_URL}