server.port=8080
spring.application.name=JBOF-Backend

# multipart limits
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

# postgres
spring.datasource.url=jdbc:postgresql://localhost:35432/jbof
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# migrations
spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration

# MinIO / S3
storage.s3.endpoint=http://localhost:9000
storage.s3.access-key=minio
storage.s3.secret-key=minio123
storage.s3.region=us-east-1
storage.s3.bucket=uploads
storage.s3.path-style=true